version: "3.8"
services:
  app:
    restart: always
    container_name: task-manager
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: production
        NODE_VERSION: 20.2.0
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'